### PR TITLE
Update default.xml

### PR DESCRIPTION
**Pull request by pavankatari**

### CODE REVIEW

**Comment by rc420head** [comment]
@anayw2001 @anayw2001 yeah, it's the pixel 3 revision I believe

**Comment by pavankatari** [comment]
git clone https://android.googlesource.com/platform/manifest

**Comment by rc420head** [comment]
@pavankatari OK we're done here

**Comment by rc420head** [comment]
Know how to do an aosp merge before making partial pull requests

**Comment by pavankatari** [comment]
i want maintainer ship for santoni (redmi 4x)

**Comment by Mazda--** [comment]
Plz sur mergy this com me for sexy time @calebcabob

**Comment by Mazda--** [comment]
Gimmie server sur @calebcabob I make fast fast rom, linaro optimized -o3 fast

**Comment by anayw2001** [comment]
@Mazda--

**Pull request closed without merging**
